version: "3.8"

services:
  payload:
    build:
      context: .
      target: runtime
    container_name: payload_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    # Only persist uploads; node_modules are already baked into the image
    volumes:
      - ./public/media:/home/node/app/public/media

  mongo:
    image: mongo:latest
    container_name: payload_mongo
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    command:
      - --storageEngine=wiredTiger
    logging:
      driver: "none"

volumes:
  mongodb_data:
